extern void scene(double t);
void textureInit(void);
void doorChange();
static void tile(double w, double d, int nw, int nd);
static void wall(double x, double y, double z, double width, double height, double depth, int numblack);
static void box(double x, double y, double z, double width, double height, double depth, int numblack);
extern GLuint exitN_Texture;
extern GLuint exit8_Texture;
extern GLuint dental_Texture;
extern GLuint parttime_Texture;
extern GLuint manner_Texture;